apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-nexus-claim
  namespace: team-cicd-controlplane
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi