apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi