apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: team-cicd-controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      # serviceAccountName: cicd-controlplane-sa
      containers:
      
        - name: jenkins
          image: 665693299603.dkr.ecr.us-east-1.amazonaws.com/jenkins:1.0.0
          # resources:
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2000m"
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1000m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          volumeMounts:
            - name: efs-volume
              mountPath: /var/jenkins_home
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
              claimName: efs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: team-cicd-controlplane
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000